// <auto-generated />
namespace BKIICT_POS_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ExpenseInfo_Added_ExpenseInfoId_PropertyAddedTo_ExpenseDetails_Class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpenseInfo_Added_ExpenseInfoId_PropertyAddedTo_ExpenseDetails_Class));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140845372_ExpenseInfo_Added_ExpenseInfoId_PropertyAddedTo_ExpenseDetails_Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
