// <auto-generated />
namespace BKIICT_POS_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PartyModel_propertyAdded_Customer_Supplier_IsDeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PartyModel_propertyAdded_Customer_Supplier_IsDeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201802210806536_PartyModel_propertyAdded_Customer_Supplier_IsDeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
